/**
 * Copyright 2011 Michael R. Lange <michael.r.lange@langmi.de>.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.langmi.spring.batch.examples.complex.jdbc.generic.export;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import org.junit.After;
import java.util.HashMap;
import java.util.Map;
import javax.sql.DataSource;
import static org.junit.Assert.*;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.batch.core.BatchStatus;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameter;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.test.JobLauncherTestUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.BatchPreparedStatementSetter;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

/**
 * JobConfigurationTest.
 *
 * @author Michael R. Lange <michael.r.lange@langmi.de> 
 */
@ContextConfiguration(locations = {
    "classpath*:spring/batch/job/complex/jdbc/jdbc-generic-export-job.xml",
    "classpath*:spring/batch/setup/**/*.xml"})
@RunWith(SpringJUnit4ClassRunner.class)
public class JdbcGenericExportJobConfigurationTest {

    /** JobLauncherTestUtils Bean. */
    @Autowired
    private JobLauncherTestUtils jobLauncherTestUtils;
    @Autowired
    private DataSource dataSource;
    private JdbcTemplate jdbcTemplate;
    /** CREATE statement for BUSINESS_OBJECTS table. */
    private static final String CREATE_TABLE_SQL = "CREATE TABLE TEST (ID INTEGER GENERATED BY DEFAULT AS IDENTITY, NAME VARCHAR (100))";
    private static final String INSERT = "INSERT INTO TEST (NAME) VALUES (?)";
    private static final String DELETE_TABLE_SQL = "DROP TABLE TEST";
    private static final String SHUTDOWN_HSQLDB = "SHUTDOWN";
    private static final String COUNT_SQL = "SELECT COUNT(*) FROM TEST";
    private static final int EXPECTED_COUNT = 40;

    /** Launch Test. */
    @Test
    public void launchJob() throws Exception {
        // Job parameters, commit.rate is set with properties file and Spring placeholder 
        Map<String, JobParameter> jobParametersMap = new HashMap<String, JobParameter>();
        jobParametersMap.put("time", new JobParameter(System.currentTimeMillis()));

        // launch the job
        JobExecution jobExecution = jobLauncherTestUtils.launchJob(new JobParameters(jobParametersMap));

        // assert job run status
        assertEquals(BatchStatus.COMPLETED, jobExecution.getStatus());

        // assert read/written items
        for (StepExecution stepExecution : jobExecution.getStepExecutions()) {
            assertEquals(EXPECTED_COUNT, stepExecution.getReadCount());
            assertEquals(EXPECTED_COUNT, stepExecution.getWriteCount());
        }

        // assert items are written successfully to database
        assertEquals(EXPECTED_COUNT, jdbcTemplate.queryForInt(COUNT_SQL));
    }

    @Before
    public void before() throws Exception {
        // provide jdbc template for setup and later assertions
        jdbcTemplate = new JdbcTemplate(dataSource);
        // setup business data table
        jdbcTemplate.execute(CREATE_TABLE_SQL);
        // insert test data
        jdbcTemplate.batchUpdate(INSERT, new BatchPreparedStatementSetter() {

            @Override
            public void setValues(PreparedStatement ps, int i) throws SQLException {
                ps.setString(1, String.valueOf(i));
            }

            @Override
            public int getBatchSize() {
                return EXPECTED_COUNT;
            }
        });
    }

    @After
    public void after() throws Exception {
        // clear table
        jdbcTemplate.execute(DELETE_TABLE_SQL);
        // shutdown HSQLDB properly
        jdbcTemplate.execute(SHUTDOWN_HSQLDB);
    }
}
